name: hi-windows

releases:
- name: sample-windows-bosh-release
  version: latest

stemcells:
- alias: windows
  os: windows2012R2
  version: latest

update:
  canaries: 1
  canary_watch_time: 30000-300000
  update_watch_time: 30000-300000
  max_in_flight: 1
  max_errors: 2
  serial: false

instance_groups:
- name: hello
  stemcell: windows
  vm_type: small
  azs:
  - z1
  - z2
  - z3
  networks:
  - name: default
  jobs:
  - name: say-hello
    release: sample-windows-bosh-release
  instances: 1
  lifecycle: service
